replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: common-nginx
  host: 129.153.213.34.nip.io   # change to your domain or <node-ip>.nip.io

