replicaCount: 2

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: common-nginx   # must match your ingress class
  host: 129.153.213.34.nip.io   # change to your domain or <node-ip>.nip.io

