apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: website-content
        configMap:
          name: {{ .Chart.Name }}-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Website on Kubernetes</title>
        <style>
          body { font-family: Arial, sans-serif; background: #f5f5f5; text-align: center; }
          .container { margin-top: 80px; }
          h1 { color: #2c3e50; }
          p { color: #34495e; font-size: 18px; }
        </style>
    </head>
    <body>
      <div class="container">
        <h1>🚀 Welcome to My Kubernetes Website!</h1>
        <p>This site is running on <b>Argo CD + Helm + Ingress</b></p>
        <p>Deployed on {{ .Chart.Name }} v{{ .Chart.AppVersion }}</p>
      </div>
    </body>
    </html>
